import Foundation

enum EmojiRussianAliases {
    static let map: [String: String] = [

        // MARK: - Общие / досуг
        "еда": "fork and knife",
        "напиток": "cup with straw",
        "напитки": "cup with straw",
        "десерт": "shortcake",
        "меню": "page facing up",
        "заказ": "shopping bags",
        "счет": "receipt",
        "чек": "receipt",
        "ресторан": "fork and knife",
        "кафе": "hot beverage",
        "бар": "cocktail glass",
        "кино": "clapper board",
        "фильм": "film frames",
        "сеанс": "ticket",
        "досуг": "confetti ball",
        "вечеринка": "party popper",
        "праздник": "party popper",
        "свидание": "red heart",
        "отдых": "palm tree",
        "прогулка": "footprints",

        // MARK: - Встречи / прогулки / тусовки
        "встреча": "confetti ball",
        "встретиться": "confetti ball",
        "сбор": "confetti ball",
        "собраться": "confetti ball",
        "компания": "confetti ball",
        "друзья": "confetti ball",
        "друг": "confetti ball",
        "подруга": "confetti ball",
        "посиделки": "confetti ball",
        "тусовка": "confetti ball",
        "туса": "confetti ball",
        "тусить": "confetti ball",
        "гулянка": "confetti ball",

        "гулять": "footprints",
        "прогуляться": "footprints",
        "променад": "footprints",

        "вечер": "crescent moon",
        "вечерок": "crescent moon",

        "выпить": "cocktail glass",
        "посидеть": "cocktail glass",
        "барчик": "cocktail glass",

        "паб": "beer mug",

        "вдвоем": "red heart",
        "пара": "red heart",
        "романтический вечер": "candle",

        // MARK: - Еда
        "пицца": "pizza",
        "бургер": "hamburger",
        "гамбургер": "hamburger",
        "чизбургер": "hamburger",
        "картошка": "french fries",
        "фри": "french fries",
        "хотдог": "hot dog",
        "сэндвич": "sandwich",
        "бутерброд": "sandwich",
        "тако": "taco",
        "буррито": "burrito",
        "донер": "stuffed flatbread",
        "шаурма": "stuffed flatbread",
        "фалафель": "falafel",
        "салат": "green salad",
        "суп": "pot of food",
        "лапша": "steaming bowl",
        "рамэн": "steaming bowl",
        "паста": "spaghetti",
        "спагетти": "spaghetti",
        "рис": "cooked rice",
        "карри": "curry rice",
        "суши": "sushi",
        "роллы": "sushi",
        "онигири": "rice ball",
        "хлеб": "bread",
        "багет": "baguette bread",
        "круассан": "croissant",
        "сыр": "cheese wedge",
        "яйцо": "egg",
        "бекон": "bacon",
        "мясо": "cut of meat",
        "стейк": "cut of meat",
        "курица": "poultry leg",
        "ножка": "poultry leg",
        "креветка": "fried shrimp",
        "рыба": "fish",
        "краб": "crab",
        "омар": "lobster",
        "устрица": "oyster",

        // MARK: - Завтрак / выпечка
        "завтрак": "pancakes",
        "блины": "pancakes",
        "панкейки": "pancakes",
        "вафли": "waffle",
        "пончик": "doughnut",
        "донат": "doughnut",
        "печенье": "cookie",
        "пряник": "cookie",
        "маффин": "cupcake",
        "кекс": "cupcake",
        "капкейк": "cupcake",
        "пирог": "pie",
        "торт": "birthday cake",
        "пирожное": "shortcake",
        "десертик": "shortcake",

        // MARK: - Сладкое / снеки
        "мороженое": "ice cream",
        "рожок": "soft ice cream",
        "джелато": "ice cream",
        "шоколад": "chocolate bar",
        "конфета": "candy",
        "леденец": "lollipop",
        "попкорн": "popcorn",
        "чипсы": "potato",
        "орехи": "peanuts",

        // MARK: - Фрукты / овощи
        "яблоко": "red apple",
        "зеленое яблоко": "green apple",
        "груша": "pear",
        "персик": "peach",
        "вишня": "cherries",
        "черешня": "cherries",
        "клубника": "strawberry",
        "черника": "blueberries",
        "виноград": "grapes",
        "арбуз": "watermelon",
        "дыня": "melon",
        "лимон": "lemon",
        "апельсин": "tangerine",
        "мандарин": "tangerine",
        "банан": "banana",
        "ананас": "pineapple",
        "манго": "mango",
        "кокос": "coconut",
        "киви": "kiwi fruit",
        "авокадо": "avocado",
        "помидор": "tomato",
        "томат": "tomato",
        "баклажан": "eggplant",
        "морковь": "carrot",
        "кукуруза": "ear of corn",
        "перец": "hot pepper",
        "чили": "hot pepper",
        "огурец": "cucumber",
        "лист": "leafy green",
        "зелень": "leafy green",
        "грибы": "mushroom",
        "гриб": "mushroom",

        // MARK: - Напитки
        "кофе": "hot beverage",
        "чай": "teacup without handle",
        "матча": "teacup without handle",
        "какао": "hot beverage",
        "вода": "potable water",
        "газировка": "cup with straw",
        "лимонад": "tropical drink",
        "сок": "beverage box",
        "смузи": "cup with straw",
        "молоко": "glass of milk",
        "коктейль": "cocktail glass",
        "дринк": "cocktail glass",
        "шейк": "cup with straw",
        "пиво": "beer mug",
        "пиво2": "clinking beer mugs",
        "вино": "wine glass",
        "шампанское": "bottle with popping cork",
        "игристое": "bottle with popping cork",
        "просекко": "bottle with popping cork",
        "виски": "tumbler glass",
        "ром": "tumbler glass",
        "коньяк": "tumbler glass",
        "ликер": "tumbler glass",
        "саке": "sake",
        "bubble tea": "bubble tea",
        "бабл ти": "bubble tea",

        // MARK: - Посуда / сервировка
        "тарелка": "plate with cutlery",
        "вилка": "fork and knife",
        "нож": "kitchen knife",
        "ложка": "spoon",
        "палочки": "chopsticks",
        "стакан": "tumbler glass",
        "бокал": "wine glass",
        "кружка": "beer mug",
        "чашка": "teacup without handle",
        "чайник": "teapot",
        "бутылка": "bottle with popping cork",

        // MARK: - Кафе / ресторан / сервис
        "официант": "bellhop bell",
        "официантка": "bellhop bell",
        "бронь": "bookmark tabs",
        "резерв": "bookmark tabs",
        "доставка": "motor scooter",
        "самовывоз": "shopping bags",
        "упаковка": "takeout box",
        "навынос": "takeout box",
        "скидка": "label",
        "акция": "label",
        "чаевые": "money with wings",
        "оплата": "credit card",
        "карта": "credit card",
        "наличные": "money bag",

        // MARK: - Кино / развлечения
        "билет": "ticket",
        "тикет": "ticket",
        "кинотеатр": "clapper board",
        "попкорнкино": "popcorn",
        "камера": "movie camera",
        "съемка": "movie camera",
        "сцена": "performing arts",
        "театр": "performing arts",
        "музыка": "musical note",
        "концерт": "microphone",
        "микрофон": "microphone",
        "танцы": "woman dancing",
        "танец": "woman dancing",
        "игра": "video game",
        "геймпад": "video game",
        "караоке": "microphone",
        "фестиваль": "confetti ball",

        // MARK: - Быстрые универсальные слова
        "вкусно": "face savoring food",
        "голод": "fork and knife",
        "голодный": "fork and knife",
        "горячее": "hot beverage",
        "острое": "hot pepper",
        "сладкое": "shortcake",
        "свежо": "leafy green",
        "любовь": "red heart",
        "романтика": "candle",
        "сюрприз": "wrapped gift"
    ]
}
